In [68]:
import pandas as pd
import numpy as np
import seaborn as sns
df = pd.read_csv('/config/workspace/Dataset/diabetes.csv')

In [69]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

- We have replaced missing values with mean.

In [70]:
df['BMI']= df['BMI'].replace(0,df['BMI'].mean())
df['BloodPressure']= df['BloodPressure'].replace(0,df['BloodPressure'].mean())
df['Glucose']= df['Glucose'].replace(0,df['Glucose'].mean())
df['Insulin']= df['Insulin'].replace(0,df['Insulin'].mean())
df['SkinThickness']= df['SkinThickness'].replace(0,df['SkinThickness'].mean())

In [71]:
df.shape

(768, 9)

In [72]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  121.681605      72.254807      26.606479  118.660163   
std       3.369578   30.436016      12.115932       9.631241   93.080358   
min       0.000000   44.000000      24.000000       7.000000   14.000000   
25%       1.000000   99.750000      64.000000      20.536458   79.799479   
50%       3.000000  117.000000      72.000000      23.000000   79.799479   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    32.450805                  0.471876   33.240885    0.348958  
std      6.875374                  0.331329   11.760232    0.476951  
min     18.200000                  0.078000   21.000000    0.000000  
25%     27.500000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [73]:
## Independent feature and dependent feature
X= df.iloc[:,:-1]
y= df['Outcome']

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [76]:
from sklearn.preprocessing import StandardScaler

In [77]:
scaler = StandardScaler()
scaler.fit(X_train)
scaler.transform(X_test)

array([[ 0.69748316, -0.79622517, -1.15754597, ...,  0.24812762,
        -0.11680393,  0.85019217],
       [-0.52953881, -0.33127247,  0.23507814, ...,  0.492445  ,
        -0.94192338, -1.03426754],
       [-0.52953881, -0.4641161 , -0.66603158, ..., -0.21176391,
        -0.91266382, -1.03426754],
       ...,
       [-1.14304979,  0.16689114,  0.64467346, ...,  0.57867466,
         0.97750343, -0.86295302],
       [ 0.69748316, -0.56374882, -0.17451719, ..., -0.21176391,
        -1.01799822,  0.33624861],
       [ 0.39072767, -1.49365422,  0.80851159, ...,  0.50681661,
        -0.91851573,  0.16493409]])

In [78]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0            6    148.0           72.0      35.000000   79.799479  33.6   
1            1     85.0           66.0      29.000000   79.799479  26.6   
2            8    183.0           64.0      20.536458   79.799479  23.3   
3            1     89.0           66.0      23.000000   94.000000  28.1   
4            0    137.0           40.0      35.000000  168.000000  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [79]:
from sklearn.linear_model import LogisticRegression

In [80]:
clfr = LogisticRegression()

In [81]:
clfr.fit(X_train,y_train)

LogisticRegression()

In [82]:
y_pred = clfr.predict(X_test)

In [83]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## Confusion matrix,accuracy score,classification report

In [84]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [85]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[126  33]
 [ 25  47]]
0.7489177489177489
              precision    recall  f1-score   support

           0       0.83      0.79      0.81       159
           1       0.59      0.65      0.62        72

    accuracy                           0.75       231
   macro avg       0.71      0.72      0.72       231
weighted avg       0.76      0.75      0.75       231



## Hyperparameter tuning

In [86]:
# GridSearchCv
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [87]:
parameters = {'penalty':('l1','l2','elasticnet',None),'C':[1,10,20]}

In [88]:
clf = GridSearchCV(clfr,param_grid=parameters,cv=5)

In [89]:
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [90]:
clf.best_params_

{'C': 10, 'penalty': 'l2'}

In [91]:
clfr=LogisticRegression(C=1,penalty=None)

In [92]:
clfr.fit(X_train,y_train)

LogisticRegression(C=1, penalty=None)

In [93]:
## Prediction
y_pred = clfr.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[124  32]
 [ 27  48]]
0.7445887445887446
              precision    recall  f1-score   support

           0       0.82      0.79      0.81       156
           1       0.60      0.64      0.62        75

    accuracy                           0.74       231
   macro avg       0.71      0.72      0.71       231
weighted avg       0.75      0.74      0.75       231



In [94]:
import pickle
pickle.dump(scaler,open('/config/workspace/Models/StandardScaler.pkl','wb'))
pickle.dump(clfr,open('/config/workspace/Models/classifier.pkl','wb'))

In [100]:
model_classifier = pickle.load(open('/config/workspace/Models/classifier.pkl','rb'))
model_classifier.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [98]:
standard_scaler = pickle.load(open('/config/workspace/Models/StandardScaler.pkl','rb'))

In [104]:
scaler.transform(X_test)

array([[ 0.69748316, -0.79622517, -1.15754597, ...,  0.24812762,
        -0.11680393,  0.85019217],
       [-0.52953881, -0.33127247,  0.23507814, ...,  0.492445  ,
        -0.94192338, -1.03426754],
       [-0.52953881, -0.4641161 , -0.66603158, ..., -0.21176391,
        -0.91266382, -1.03426754],
       ...,
       [-1.14304979,  0.16689114,  0.64467346, ...,  0.57867466,
         0.97750343, -0.86295302],
       [ 0.69748316, -0.56374882, -0.17451719, ..., -0.21176391,
        -1.01799822,  0.33624861],
       [ 0.39072767, -1.49365422,  0.80851159, ...,  0.50681661,
        -0.91851573,  0.16493409]])

In [105]:
pca = decomposition.PCA(n_components=3)
pca.fit(X_test)
X_test = pca.transform(X_test)
X_test

NameError: name 'decomposition' is not defined